apiVersion: extensions/v1beta1

kind: Deployment

metadata:

  name: username

spec:

  replicas: 1

  template:

    metadata:

      labels:

        app: username

    spec:

      containers:

      - name: username-container

        image: docker.io/subhamverma2407/username:first

        ports:

        - containerPort: 80


